export type Bar={time:string;open:number;high:number;low:number;close:number;volume:number;id?:number};
export type MarketSnapshot={ticker:string;provider:string;updated_at:string;bars:Bar[]};
export type SimulationConfig={seed:number;startPrice:number;volatility:number;drift:number;intervalMs:number};
export function movingAverage(values:number[],window:number):Array<number|null>{return values.map((_,i)=>i+1<window?null:values.slice(i-window+1,i+1).reduce((a,b)=>a+b,0)/window)}
export function exponentialMovingAverage(values:number[],window:number):Array<number|null>{if(!values.length)return[];const alpha=2/(window+1);let ema=values[0];return values.map((value,i)=>{ema=i===0?value:alpha*value+(1-alpha)*ema;return i+1<window?null:ema})}
export function bollingerBands(values:number[],window=20,multiplier=2){const middle=movingAverage(values,window);return values.map((_,i)=>{if(i+1<window)return{middle:null,upper:null,lower:null};const sample=values.slice(i-window+1,i+1);const mean=middle[i] as number;const deviation=Math.sqrt(sample.reduce((sum,value)=>sum+(value-mean)**2,0)/window);return{middle:mean,upper:mean+multiplier*deviation,lower:mean-multiplier*deviation}})}
export function deterministicNoise(seed:number,index:number){let value=(seed+index*0x6d2b79f5)|0;value=Math.imul(value^(value>>>15),value|1);value^=value+Math.imul(value^(value>>>7),value|61);return((value^(value>>>14))>>>0)/4294967296}
export function nextSimulatedBar(previous:Bar,config:SimulationConfig,index:number,shock=0,volumeSpike=false):Bar{const u1=Math.max(deterministicNoise(config.seed,index*2),1e-9),u2=deterministicNoise(config.seed,index*2+1);const normal=Math.sqrt(-2*Math.log(u1))*Math.cos(2*Math.PI*u2);const dt=1/(252*390);const close=previous.close*Math.exp((config.drift-.5*config.volatility**2)*dt+config.volatility*Math.sqrt(dt)*normal+shock);const range=Math.abs(normal)*config.volatility*Math.sqrt(dt)*previous.close*.75+.025;const open=previous.close,high=Math.max(open,close)+range,low=Math.max(.01,Math.min(open,close)-range);const baseVolume=Math.round(85000*(.65+deterministicNoise(config.seed,index*3+7)));return{id:index,time:new Date(Date.UTC(2026,6,23,14,30)+index*60000).toISOString(),open,high,low,close,volume:volumeSpike?baseVolume*8:baseVolume}}
export function generateBars(config:SimulationConfig,count=180){const first:Bar={id:0,time:new Date(Date.UTC(2026,6,23,14,30)).toISOString(),open:config.startPrice,high:config.startPrice,low:config.startPrice,close:config.startPrice,volume:75000};const bars=[first];for(let i=1;i<count;i++)bars.push(nextSimulatedBar(bars.at(-1) as Bar,config,i));return bars}
export function normalizeBars(bars:Bar[],limit=240){const unique=new Map<string,Bar>();for(const raw of bars){const bar={...raw,open:Number(raw.open),high:Number(raw.high),low:Number(raw.low),close:Number(raw.close),volume:Number(raw.volume)};if(![bar.open,bar.high,bar.low,bar.close,bar.volume].every(Number.isFinite)||bar.low>Math.min(bar.open,bar.close)||bar.high<Math.max(bar.open,bar.close)||bar.volume<0)continue;unique.set(bar.time,bar)}return[...unique.values()].sort((a,b)=>a.time.localeCompare(b.time)).slice(-limit)}
export function reconnectDelay(attempt:number,max=30000){return Math.min(1000*2**Math.max(0,attempt-1),max)}
